'''********************************************************************************** 
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.



Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
**********************************************************************************'''

class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        
        d = dict()
        for i in s:
            if i not in d.keys():
                d[i]=1
            else:
                d[i]+=1
        for i in t:
            if i not in d.keys():
                return i
            else:
                d[i]-=1
        for i in d.keys():
            if d[i]!=0:
                return i
                        
